
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex("legislators").del()
    .then(function () {
      // Inserts seed entries
      return knex("legislators").insert([{
        "title": "Representative",
        "name": "Arndt, Jeni James",
        "district": 53,
        "party": "Democrat",
        "phone": "303-866-2917",
        "email": "jeni.arndt.house@state.co.us",
        "occupation": "Legislator",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_arndt-co-17.jpg?itok=BOPWvPGK",
        "full_name": "Jeni James Arndt",
        "last_name": "Arndt",
        "sponsor_name": "Rep. A. Arndt",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Becker, Jon",
        "district": 65,
        "party": "Republican",
        "phone": "303-866-3706",
        "email": "jon.becker.house@state.co.us",
        "occupation": "Telecom Executive",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_beckerjon-co-17.jpg?itok=uLkf26nZ",
        "full_name": "KC Becker",
        "last_name": "Becker K.",
        "sponsor_name": "Rep. B. Becker",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Becker, KC",
        "district": 13,
        "party": "Democrat",
        "phone": "303-866-2578",
        "email": "kcbecker.house@state.co.us",
        "occupation": "Attorney",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_beckerkc-co-17.jpg?itok=2NxgoftS",
        "full_name": "Jon Becker",
        "last_name": "Becker J.",
        "sponsor_name": "Rep. B. Becker",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Beckman, Susan",
        "district": 38,
        "party": "Republican",
        "phone": "303-866-2953",
        "email": "susan.beckman.house@state.co.us",
        "occupation": "Legislator",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_beckman-co-17.jpg?itok=QGxmVSqN",
        "full_name": "Susan Beckman",
        "last_name": "Beckman",
        "sponsor_name": "Rep. B. Beckman",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Benavidez, Adrienne",
        "district": 32,
        "party": "Democrat",
        "phone": "303-866-2964",
        "email": "adrienne.benavidez.house@state.co.us",
        "occupation": "Attorney",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_benavidez-co-17.jpg?itok=Gs0Kg2Y-",
        "full_name": "Adrienne Benavidez",
        "last_name": "Benavidez",
        "sponsor_name": "Rep. B. Benavidez",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Bridges, Jeff",
        "district": 3,
        "party": "Democrat",
        "phone": "303-866-2921",
        "email": "jeff.bridges.house@state.co.us",
        "occupation": "Legislator",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_bridges-co-17.jpg?itok=9XryX75E",
        "full_name": "Jeff Bridges",
        "last_name": "Bridges",
        "sponsor_name": "Rep. B. Bridges",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Buck, Perry",
        "district": 49,
        "party": "Republican",
        "phone": "303-866-2907",
        "email": "perrybuck49@gmail.com",
        "occupation": "Event Planning",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_buck-co-17.jpg?itok=qvls0S3G",
        "full_name": "Perry Buck",
        "last_name": "Buck",
        "sponsor_name": "Rep. B. Buck",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Buckner, Janet",
        "district": 40,
        "party": "Democrat",
        "phone": "303-866-2944",
        "email": "janet.buckner.house@state.co.us",
        "occupation": "Retired Sales Executive",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_buckner-co-17.jpg?itok=f2JoL_G7",
        "full_name": "Janet Buckner",
        "last_name": "Buckner",
        "sponsor_name": "Rep. B. Buckner",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Carver, Terri",
        "district": 20,
        "party": "Republican",
        "phone": "303-866-2191",
        "email": "terri.carver.house@state.co.us",
        "occupation": "Legislator",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_carver-co-17.jpg?itok=tQSb6j62",
        "full_name": "Terri Carver",
        "last_name": "Carver",
        "sponsor_name": "Rep. C. Carver",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Catlin, Marc",
        "district": 58,
        "party": "Republican",
        "phone": "303-866-2955",
        "email": "marc.catlin.house@state.co.us",
        "occupation": "Legislator",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_catlin-co-17.jpg?itok=E9x8Uyyk",
        "full_name": "Marc Catlin",
        "last_name": "Catlin",
        "sponsor_name": "Rep. C. Catlin",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Coleman, James",
        "district": 7,
        "party": "Democrat",
        "phone": "303-866-2909",
        "email": "james.coleman.house@state.co.us",
        "occupation": "V.P. Community Engagement ACE Scholarships",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_coleman-co-17.jpg?itok=ryJb8wPe",
        "full_name": "James Coleman",
        "last_name": "Coleman",
        "sponsor_name": "Rep. C. Coleman",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Covarrubias, Phil",
        "district": 56,
        "party": "Republican",
        "phone": "303-866-2912",
        "email": "Phil.Covarrubias.house@state.co.us",
        "occupation": "Lead Foreman/Project Manager",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_1covarrubias-co-17_1.jpg?itok=JwFPMO92",
        "full_name": "Phil Covarrubias",
        "last_name": "Covarrubias",
        "sponsor_name": "Rep. C. Covarrubias",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Danielson, Jessie",
        "district": 24,
        "party": "Democrat",
        "phone": "303-866-5522",
        "email": "jessie.danielson.house@state.co.us",
        "occupation": "Legislator",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_danielson-co-17.jpg?itok=DYr_49DF",
        "full_name": "Jessie Danielson",
        "last_name": "Danielson",
        "sponsor_name": "Rep. D. Danielson",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Duran, Crisanta",
        "district": 5,
        "party": "Democrat",
        "phone": "303-866-2925",
        "email": "crisanta.duran.house@state.co.us",
        "occupation": "Attorney",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_h-speaker%20duran%20-17.jpg?itok=aPBQpZ1i",
        "full_name": "Crisanta Duran",
        "last_name": "Duran",
        "sponsor_name": "Rep. D. Duran",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Esgar, Daneya",
        "district": 46,
        "party": "Democrat",
        "phone": "303-866-2968",
        "email": "daneya.esgar.house@state.co.us",
        "occupation": "Legislator",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_esgar-co-17.jpg?itok=WmxetJSX",
        "full_name": "Daneya Esgar",
        "last_name": "Esgar",
        "sponsor_name": "Rep. E. Esgar",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Everett, Justin",
        "district": 22,
        "party": "Republican",
        "phone": "303-866-2927",
        "email": "justin.everett.house@state.co.us",
        "occupation": "Mediator/Arbitrator",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_everett-co-15.jpg?itok=TruPPoB3",
        "full_name": "Justin Everett",
        "last_name": "Everett",
        "sponsor_name": "Rep. E. Everett",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Exum, Tony",
        "district": 17,
        "party": "Democrat",
        "phone": "303-866-3069",
        "email": "tony.exum.house@state.co.us",
        "occupation": "Retired Firefighter",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_exum-co-17.jpg?itok=BAz9Yygu",
        "full_name": "Tony Exum",
        "last_name": "Exum",
        "sponsor_name": "Rep. E. Exum",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Foote, Mike",
        "district": 12,
        "party": "Democrat",
        "phone": "303-866-2920",
        "email": "mike.foote.house@state.co.us",
        "occupation": "Attorney",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_foote-co-17.jpg?itok=XVGfigl7",
        "full_name": "Mike Foote",
        "last_name": "Foote",
        "sponsor_name": "Rep. F. Foote",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Garnett, Alec",
        "district": 2,
        "party": "Democrat",
        "phone": "303-866-2911",
        "email": "alec.garnett.house@state.co.us",
        "occupation": "Legislator",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_garnett-co-17.jpg?itok=uwR0p2IS",
        "full_name": "Alec Garnett",
        "last_name": "Garnett",
        "sponsor_name": "Rep. G. Garnett",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Ginal, Joann",
        "district": 52,
        "party": "Democrat",
        "phone": "303-866-4569",
        "email": "joannginal@yahoo.com",
        "occupation": "Reproductive Endocrinologist",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_ginal-co-17.jpg?itok=rg01mgi5",
        "full_name": "Joann Ginal",
        "last_name": "Ginal",
        "sponsor_name": "Rep. G. Ginal",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Gray, Matt",
        "district": 33,
        "party": "Democrat",
        "phone": "303-866-4667",
        "email": "matt@matthewgray.us",
        "occupation": "Attorney",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_gray-co-17.jpg?itok=1fstE2Kv",
        "full_name": "Matt Gray",
        "last_name": "Gray",
        "sponsor_name": "Rep. G. Gray",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Hamner, Millie",
        "district": 61,
        "party": "Democrat",
        "phone": "303-866-2952",
        "email": "rephamner@gmail.com",
        "occupation": "Legislator",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_hamner-co-17.jpg?itok=fVh61CjX",
        "full_name": "Millie Hamner",
        "last_name": "Hamner",
        "sponsor_name": "Rep. H. Hamner",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Hansen, Chris",
        "district": 6,
        "party": "Democrat",
        "phone": "303-866-2967",
        "email": "chris.hansen.house@state.co.us",
        "occupation": "Consultant",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_hansen-co-17.jpg?itok=TtlOzE2U",
        "full_name": "Chris Hansen",
        "last_name": "Hansen",
        "sponsor_name": "Rep. H. Hansen",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Herod, Leslie",
        "district": 8,
        "party": "Democrat",
        "phone": "303-866-2959",
        "email": "leslie.herod.house@state.co.us",
        "occupation": "Legislator",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_herod-co-17.jpg?itok=plXxMhIY",
        "full_name": "Leslie Herod",
        "last_name": "Herod",
        "sponsor_name": "Rep. H. Herod",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Hooton, Edie",
        "district": 10,
        "party": "Democrat",
        "phone": "303-866-2915",
        "email": "edie.hooton.house@state.co.us",
        "occupation": "Legislator",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_hooton-co-17.jpg?itok=6N87z25C",
        "full_name": "Edie Hooton",
        "last_name": "Hooton",
        "sponsor_name": "Rep. H. Hooton",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Humphrey, Stephen",
        "district": 48,
        "party": "Republican",
        "phone": "303-866-2943",
        "email": "rephumphrey48@yahoo.com",
        "occupation": "Therapist and Marriage Counselor",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_humphrey-co-17.jpg?itok=bXKFzgmz",
        "full_name": "Stephen Humphrey",
        "last_name": "Humphrey",
        "sponsor_name": "Rep. H. Humphrey",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Jackson, Dominique",
        "district": 42,
        "party": "Democrat",
        "phone": "303-866-3911",
        "email": "dominique.jackson.house@state.co.us",
        "occupation": "Legislator",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_jackson-co-17.jpg?itok=yaBnFiej",
        "full_name": "Dominique Jackson",
        "last_name": "Jackson",
        "sponsor_name": "Rep. J. Jackson",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Kennedy, Chris",
        "district": 23,
        "party": "Democrat",
        "phone": "303-866-2951",
        "email": "chris.kennedy.house@state.co.us",
        "occupation": "Legislator",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_kennedy-co-17.jpg?itok=9tRxFCT3",
        "full_name": "Chris Kennedy",
        "last_name": "Kennedy",
        "sponsor_name": "Rep. K. Kennedy",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Kraft-Tharp, Tracy",
        "district": 29,
        "party": "Democrat",
        "phone": "303-866-2950",
        "email": "reptracy29@gmail.com",
        "occupation": "Small Business Owner",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_kraft-tharp-c-17.jpg?itok=rSvuyKcr",
        "full_name": "Tracy Kraft-Tharp",
        "last_name": "Kraft-Tharp",
        "sponsor_name": "Rep. K. Kraft-Tharp",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Landgraf, Lois",
        "district": 21,
        "party": "Republican",
        "phone": "303-866-2946",
        "email": "lois.landgraf.house@state.co.us",
        "occupation": "Legislator",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_landgraf-c-17.jpg?itok=pewaRwPq",
        "full_name": "Lois Landgraf",
        "last_name": "Landgraf",
        "sponsor_name": "Rep. L. Landgraf",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Lawrence, Polly",
        "district": 39,
        "party": "Republican",
        "phone": "303-866-2935",
        "email": "polly.lawrence.house@state.co.us",
        "occupation": "Construction",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_lawrence-co-17.jpg?itok=b2-EgbCS",
        "full_name": "Polly Lawrence",
        "last_name": "Lawrence",
        "sponsor_name": "Rep. L. Lawrence",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Lebsock, Steve",
        "district": 34,
        "party": "Republican",
        "phone": "303-866-2931",
        "email": "steve.lebsock.house@state.co.us",
        "occupation": "Legislator [Expelled]",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_lebsock-co-17.jpg?itok=Gd0_cpyx",
        "full_name": "Steve Lebsock",
        "last_name": "Lebsock",
        "sponsor_name": "Rep. S. Lebsock",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Lee, Pete",
        "district": 18,
        "party": "Democrat",
        "phone": "303-866-2932",
        "email": "pete.lee.house@state.co.us",
        "occupation": "Legislator",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_lee-co-17.jpg?itok=xUslw-MB",
        "full_name": "Pete Lee",
        "last_name": "Lee",
        "sponsor_name": "Rep. L. Lee",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Leonard, Timothy",
        "district": 25,
        "party": "Republican",
        "phone": "303-866-2582",
        "email": "tim.leonard.house@state.co.us",
        "occupation": "Commercial Real Estate Business Owner",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_leonard-co-17.jpg?itok=po_QlVR7",
        "full_name": "Timothy Leonard",
        "last_name": "Leonard",
        "sponsor_name": "Rep. L. Leonard",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Lewis, Kimmi",
        "district": 64,
        "party": "Republican",
        "phone": "303-866-2398",
        "email": "kimmi.lewis.house@state.co.us",
        "occupation": "Cattle Producer",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_lewis-co-17.jpg?itok=PW_90ZHJ",
        "full_name": "Kimmi Lewis",
        "last_name": "Lewis",
        "sponsor_name": "Rep. L. Lewis",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Liston, Larry",
        "district": 16,
        "party": "Republican",
        "phone": "303-866-2937",
        "email": "larry.liston.house@state.co.us",
        "occupation": "Vice President, Royal Bank of Canada (Ret.)",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_liston-co-17.jpg?itok=wU3y2Van",
        "full_name": "Larry Liston",
        "last_name": "Liston",
        "sponsor_name": "Rep. L. Liston",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Lontine, Susan",
        "district": 1,
        "party": "Democrat",
        "phone": "303-866-2966",
        "email": "susan.lontine.house@state.co.us",
        "occupation": "Legislator",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_lontine-co-17.jpg?itok=6IbkapD2",
        "full_name": "Susan Lontine",
        "last_name": "Lontine",
        "sponsor_name": "Rep. L. Lontine",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Lundeen, Paul",
        "district": 19,
        "party": "Republican",
        "phone": "303-866-2924",
        "email": "paul.lundeen.house@state.co.us",
        "occupation": "Entreprenuer",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_lundeen-co-17.jpg?itok=c-OFvapt",
        "full_name": "Paul Lundeen",
        "last_name": "Lundeen",
        "sponsor_name": "Rep. L. Lundeen",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "McKean, Hugh",
        "district": 51,
        "party": "Republican",
        "phone": "303-866-2947",
        "email": "hugh.mckean.house@state.co.us",
        "occupation": "General Contractor",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_mckean-co-17.jpg?itok=ZUm8UlLS",
        "full_name": "Hugh McKean",
        "last_name": "McKean",
        "sponsor_name": "Rep. M. McKean",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "McLachlan, Barbara",
        "district": 59,
        "party": "Democrat",
        "phone": "303-866-2914",
        "email": "barbara.mclachlan.house@state.co.us",
        "occupation": "Legislator",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_mclachlan-co-17.jpg?itok=VnnEiNRM",
        "full_name": "Barbara McLachlan",
        "last_name": "McLachlan",
        "sponsor_name": "Rep. M. McLachlan",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Melton, Jovan",
        "district": 41,
        "party": "Democrat",
        "phone": "303-866-2919",
        "email": "jovan.melton.house@state.co.us",
        "occupation": "Consultant",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_melton-co-17.jpg?itok=IszgAPL3",
        "full_name": "Jovan Melton",
        "last_name": "Melton",
        "sponsor_name": "Rep. M. Melton",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Michaelson Jenet, Dafna",
        "district": 30,
        "party": "Democrat",
        "phone": "303-866-2945",
        "email": "dafna.michaelson.jenet.house@state.co.us",
        "occupation": "Speaker/Trainer",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_michaelson_jenet-co-17.jpg?itok=TPdtl5J2",
        "full_name": "Dafna Michaelson Jenet",
        "last_name": "Michaelson Jenet",
        "sponsor_name": "Rep. M. Michaelson Jenet",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Neville, Patrick",
        "district": 45,
        "party": "Republican",
        "phone": "303-866-5523",
        "email": "patrick.neville.house@state.co.us",
        "occupation": "Business Owner",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_nevillep-co-17.jpg?itok=wg1chcnL",
        "full_name": "Patrick Neville",
        "last_name": "Neville P.",
        "sponsor_name": "Rep. N. Neville",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Pabon, Dan",
        "district": 4,
        "party": "Democrat",
        "phone": "303-866-2954",
        "email": "dan.pabon.house@state.co.us",
        "occupation": "Engineer",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_pabon-co-17.jpg?itok=bCRtYt5h",
        "full_name": "Dan Pabon",
        "last_name": "Pabon",
        "sponsor_name": "Rep. P. Pabon",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Pettersen, Brittany",
        "district": 28,
        "party": "Democrat",
        "phone": "303-866-2939",
        "email": "brittany.pettersen.house@state.co.us",
        "occupation": "Legislator",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_pettersen-co-17.jpg?itok=Sf33p1r8",
        "full_name": "Brittany Pettersen",
        "last_name": "Pettersen",
        "sponsor_name": "Rep. P. Pettersen",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Rankin, Bob",
        "district": 57,
        "party": "Republican",
        "phone": "303-866-2949",
        "email": "bob.rankin.house@state.co.us",
        "occupation": "Legislator",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_rankin-c-17.jpg?itok=9adePs6f",
        "full_name": "Bob Rankin",
        "last_name": "Rankin",
        "sponsor_name": "Rep. R. Rankin",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Ransom, Kim",
        "district": 44,
        "party": "Republican",
        "phone": "303-866-2933",
        "email": "kim.ransom.house@state.co.us",
        "occupation": "Legislator",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_ransom-co-17.jpg?itok=L5TFc_HC",
        "full_name": "Kim Ransom",
        "last_name": "Ransom",
        "sponsor_name": "Rep. R. Ransom",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Reyher, Judy",
        "district": 47,
        "party": "Republican",
        "phone": "303-866-2905",
        "email": "judy.reyher.house@state.co.us",
        "occupation": "Business Owner",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_jreyher.jpg?itok=NVL9ATKd",
        "full_name": "Judy Reyher",
        "last_name": "Reyher",
        "sponsor_name": "Rep. R. Reyher",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Roberts, Dylan",
        "district": 26,
        "party": "Democrat",
        "phone": "303-866-2923",
        "email": "dylan.roberts.house@state.co.us",
        "occupation": "Deputy District Attorney",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_droberts.jpg?itok=yacIzp6v",
        "full_name": "Dylan Roberts",
        "last_name": "Roberts",
        "sponsor_name": "Rep. R. Roberts",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Rosenthal, Paul",
        "district": 9,
        "party": "Democrat",
        "phone": "303-866-2910",
        "email": "paulrosenthal5280@gmail.com",
        "occupation": "Teacher",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_rosenthal-co-17.jpg?itok=nELX5lKv",
        "full_name": "Paul Rosenthal",
        "last_name": "Rosenthal",
        "sponsor_name": "Rep. R. Rosenthal",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Saine, Lori",
        "district": 63,
        "party": "Republican",
        "phone": "303-866-2906",
        "email": "lori.saine.house@state.co.us",
        "occupation": "Sales Director",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_saine-co-15.jpg?itok=SFzUfDz4",
        "full_name": "Lori Saine",
        "last_name": "Saine",
        "sponsor_name": "Rep. S. Saine",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Salazar, Joseph",
        "district": 31,
        "party": "Democrat",
        "phone": "303-866-2918",
        "email": "joseph.salazar.house@state.co.us",
        "occupation": "Civil Rights Attorney/Professor",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_salazar-co-17.jpg?itok=Z8NfsAVV",
        "full_name": "Joseph Salazar",
        "last_name": "Salazar",
        "sponsor_name": "Rep. S. Salazar",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Sandridge, Shane",
        "district": 14,
        "party": "Republican",
        "phone": "303-866-2965",
        "email": "shane.sandridge.house@state.co.us",
        "occupation": "Investment Consultant",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_ssandridge.jpg?itok=N74di2rN",
        "full_name": "Shane Sandridge",
        "last_name": "Sandridge",
        "sponsor_name": "Rep. S. Sandridge",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Sias, Lang",
        "district": 27,
        "party": "Republican",
        "phone": "303-866-2962",
        "email": "lang.sias.house@state.co.us",
        "occupation": "Commercial Pilot",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_sias-co-17.jpg?itok=BZr9IO5e",
        "full_name": "Lang Sias",
        "last_name": "Sias",
        "sponsor_name": "Rep. S. Sias",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Singer, Jonathan",
        "district": 11,
        "party": "Democrat",
        "phone": "303-866-2780",
        "email": "jonathan.singer.house@state.co.us",
        "occupation": "Social Worker",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_singer-co-17.jpg?itok=KF_qV1tj",
        "full_name": "Jonathan Singer",
        "last_name": "Singer",
        "sponsor_name": "Rep. S. Singer",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Thurlow, Dan",
        "district": 55,
        "party": "Republican",
        "phone": "303-866-3068",
        "email": "danthurlow55@gmail.com",
        "occupation": "Legislator",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_thurlow-co-17.jpg?itok=NtAAyo7J",
        "full_name": "Dan Thurlow",
        "last_name": "Thurlow",
        "sponsor_name": "Rep. T. Thurlow",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Valdez, Donald",
        "district": 62,
        "party": "Democrat",
        "phone": "303-866-2916",
        "email": "donald.valdez.house@state.co.us",
        "occupation": "Farmer/Legislator",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_valdez-co-17.jpg?itok=mLOEjazc",
        "full_name": "Donald Valdez",
        "last_name": "Valdez",
        "sponsor_name": "Rep. V. Valdez",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Van Winkle, Kevin",
        "district": 43,
        "party": "Republican",
        "phone": "303-866-2936",
        "email": "kevin.vanwinkle.house@state.co.us",
        "occupation": "Small Business Owner",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_vanwinkle-co-17.jpg?itok=PFGbxzPC",
        "full_name": "Kevin Van Winkle",
        "last_name": "Van Winkle",
        "sponsor_name": "Rep. V. Van Winkle",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Weissman, Mike",
        "district": 36,
        "party": "Democrat",
        "phone": "303-866-2942",
        "email": "mike.weissman.house@state.co.us",
        "occupation": "Attorney",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_weissman-co-17.jpg?itok=AKqlonZ7",
        "full_name": "Mike Weissman",
        "last_name": "Weissman",
        "sponsor_name": "Rep. W. Weissman",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Willett, Yeulin",
        "district": 54,
        "party": "Republican",
        "phone": "303-866-2583",
        "email": "yeulin.willett.house@state.co.us",
        "occupation": "Attorney",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_willett-co-15.jpg?itok=TzCCVvun",
        "full_name": "Yeulin Willett",
        "last_name": "Willett",
        "sponsor_name": "Rep. W. Willett",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Williams, Dave",
        "district": 15,
        "party": "Republican",
        "phone": "303-866-5525",
        "email": "dave.williams.house@state.co.us",
        "occupation": "Manufacturing Executive",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_williams-co-17.jpg?itok=uqx3Ec23",
        "full_name": "Dave Williams",
        "last_name": "Williams D.",
        "sponsor_name": "Rep. W. Williams",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Wilson, James",
        "district": 60,
        "party": "Republican",
        "phone": "303-866-2747",
        "email": "representativewilson@gmail.com",
        "occupation": "Retired",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_wilson-co-17.jpg?itok=G1ZG_S3K",
        "full_name": "James Wilson",
        "last_name": "Wilson",
        "sponsor_name": "Rep. W. Wilson",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Winkler, Alexander \"Skinny",
        "district": 34,
        "party": "Republican",
        "phone": "303-866-2931",
        "email": "alexander.winkler.house@state.co.us",
        "occupation": "Business Owner",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_h-winkler-2018.jpg?itok=n9dbr5lD",
        "full_name": "Alexander \"Skinny\" Winkler",
        "last_name": "Winkler",
        "sponsor_name": "Rep. W. Winkler",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Winter, Faith",
        "district": 35,
        "party": "Democrat",
        "phone": "303-866-2843",
        "email": "faith.winter.house@state.co.us",
        "occupation": "Non-profit Consultant",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_winter-co-17.jpg?itok=lXe6dNx_",
        "full_name": "Faith Winter",
        "last_name": "Winter",
        "sponsor_name": "Rep. W. Winter",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Wist, Cole",
        "district": 37,
        "party": "Republican",
        "phone": "303-866-5510",
        "email": "cole.wist.house@state.co.us",
        "occupation": "Attorney",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_h-wist_cole_add_2016.jpg?itok=vU1LOP3W",
        "full_name": "Cole Wist",
        "last_name": "Wist",
        "sponsor_name": "Rep. W. Wist",
        "chamber": "House"
      }, {
        "title": "Representative",
        "name": "Young, Dave",
        "district": 50,
        "party": "Democrat",
        "phone": "303-866-2929",
        "email": "dave.young.house@state.co.us",
        "occupation": "College Instructor",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_young-co-17.jpg?itok=U-BZUl-d",
        "full_name": "Dave Young",
        "last_name": "Young",
        "sponsor_name": "Rep. Y. Young",
        "chamber": "House"
      }, {
        "title": "Senator",
        "name": "Aguilar, Irene",
        "district": 32,
        "party": "Democrat",
        "phone": "303-866-4852",
        "email": "irene.aguilar.senate@state.co.us",
        "occupation": "Physician",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_s-aguilar%2C%20irene.jpg?itok=LPm4bPc7",
        "full_name": "Irene Aguilar",
        "last_name": "Aguilar",
        "sponsor_name": "Sen. I. Aguilar",
        "chamber": "Senate"
      }, {
        "title": "Senator",
        "name": "Baumgardner, Randy",
        "district": 8,
        "party": "Republican",
        "phone": "303-866-5292",
        "email": "randy.baumgardner.senate@state.co.us",
        "occupation": "Rancher/Citizen Legislator",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_s-baumgardner%2C%20randy.jpg?itok=Ju2nXDoI",
        "full_name": "Randy Baumgardner",
        "last_name": "Baumgardner",
        "sponsor_name": "Sen. R. Baumgardner",
        "chamber": "Senate"
      }, {
        "title": "Senator",
        "name": "Cooke, John",
        "district": 13,
        "party": "Republican",
        "phone": "303-866-4451",
        "email": "john.cooke.senate@state.co.us",
        "occupation": "Retired Sheriff",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_cooke-co-17.jpg?itok=wLGFmGj7",
        "full_name": "John Cooke",
        "last_name": "Cooke",
        "sponsor_name": "Sen. J. Cooke",
        "chamber": "Senate"
      }, {
        "title": "Senator",
        "name": "Coram, Don",
        "district": 6,
        "party": "Republican",
        "phone": "303-866-4884",
        "email": "don.coram.senate@state.co.us",
        "occupation": "Rancher/Mining",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_coram-co-17.jpg?itok=ybS1ZNG_",
        "full_name": "Don Coram",
        "last_name": "Coram",
        "sponsor_name": "Sen. D. Coram",
        "chamber": "Senate"
      }, {
        "title": "Senator",
        "name": "Court, Lois",
        "district": 31,
        "party": "Democrat",
        "phone": "303-866-4861",
        "email": "lois.court.senate@state.co.us",
        "occupation": "State Senator",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_court-co-17.jpg?itok=Vgky5AAh",
        "full_name": "Lois Court",
        "last_name": "Court",
        "sponsor_name": "Sen. L. Court",
        "chamber": "Senate"
      }, {
        "title": "Senator",
        "name": "Crowder, Larry",
        "district": 35,
        "party": "Republican",
        "phone": "303-866-4875",
        "email": "larry.crowder.senate@state.co.us",
        "occupation": "Rancher/Farmer",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_crowder-co-17.jpg?itok=ccBlL26h",
        "full_name": "Larry Crowder",
        "last_name": "Crowder",
        "sponsor_name": "Sen. L. Crowder",
        "chamber": "Senate"
      }, {
        "title": "Senator",
        "name": "Donovan, Kerry",
        "district": 5,
        "party": "Democrat",
        "phone": "303-866-4871",
        "email": "kerry.donovan.senate@state.co.us",
        "occupation": "Rancher",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_donovan-co-17.jpg?itok=xDOsHs_B",
        "full_name": "Kerry Donovan",
        "last_name": "Donovan",
        "sponsor_name": "Sen. K. Donovan",
        "chamber": "Senate"
      }, {
        "title": "Senator",
        "name": "Fenberg, Stephen",
        "district": 18,
        "party": "Democrat",
        "phone": "303-866-4872",
        "email": "stephen.fenberg.senate@state.co.us",
        "occupation": "Partner, Bread Bar",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_fenberg-co-17.jpg?itok=m9sVMgOg",
        "full_name": "Stephen Fenberg",
        "last_name": "Fenberg",
        "sponsor_name": "Sen. S. Fenberg",
        "chamber": "Senate"
      }, {
        "title": "Senator",
        "name": "Fields, Rhonda",
        "district": 29,
        "party": "Democrat",
        "phone": "303-866-4879",
        "email": "rhonda.fields.senate@state.co.us",
        "occupation": "Legislator",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_fields-co-17.jpg?itok=NZ885Ux1",
        "full_name": "Rhonda Fields",
        "last_name": "Fields",
        "sponsor_name": "Sen. R. Fields",
        "chamber": "Senate"
      }, {
        "title": "Senator",
        "name": "Garcia, Leroy",
        "district": 3,
        "party": "Democrat",
        "phone": "303-866-4878",
        "email": "leroy.garcia.senate@state.co.us",
        "occupation": "Faculty Member, Pueblo Community College",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_s-garcia%2C%20leroy.jpg?itok=R636cvVe",
        "full_name": "Leroy Garcia",
        "last_name": "Garcia",
        "sponsor_name": "Sen. L. Garcia",
        "chamber": "Senate"
      }, {
        "title": "Senator",
        "name": "Gardner, Bob",
        "district": 12,
        "party": "Republican",
        "phone": "303-866-4880",
        "email": "bob.gardner.senate@state.co.us",
        "occupation": "Attorney",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_gardner-co-17.jpg?itok=Szs8CoL7",
        "full_name": "Bob Gardner",
        "last_name": "Gardner",
        "sponsor_name": "Sen. B. Gardner",
        "chamber": "Senate"
      }, {
        "title": "Senator",
        "name": "Grantham, Kevin",
        "district": 2,
        "party": "Republican",
        "phone": "303-866-4877",
        "email": "kevin.grantham.senate@state.co.us",
        "occupation": "Real Estate Appraiser",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_grantham.jpg?itok=D5Y5i4MY",
        "full_name": "Kevin Grantham",
        "last_name": "Grantham",
        "sponsor_name": "Sen. K. Grantham",
        "chamber": "Senate"
      }, {
        "title": "Senator",
        "name": "Guzman, Lucia",
        "district": 34,
        "party": "Democrat",
        "phone": "303-866-4862",
        "email": "lucia.guzman.senate@state.co.us",
        "occupation": "Senator",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_guzman-co-17.jpg?itok=wxgGlnl2",
        "full_name": "Lucia Guzman",
        "last_name": "Guzman",
        "sponsor_name": "Sen. L. Guzman",
        "chamber": "Senate"
      }, {
        "title": "Senator",
        "name": "Hill, Owen",
        "district": 10,
        "party": "Republican",
        "phone": "303-866-2737",
        "email": "owen.hill.senate@state.co.us",
        "occupation": "Project Manager",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_hill-co-17.jpg?itok=-wkltSd_",
        "full_name": "Owen Hill",
        "last_name": "Hill",
        "sponsor_name": "Sen. O. Hill",
        "chamber": "Senate"
      }, {
        "title": "Senator",
        "name": "Holbert, Chris",
        "district": 30,
        "party": "Republican",
        "phone": "303-866-4881",
        "email": "chris.holbert.senate@state.co.us",
        "occupation": "Consultant",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_holbert-co-17.jpg?itok=9DDx-oPQ",
        "full_name": "Chris Holbert",
        "last_name": "Holbert",
        "sponsor_name": "Sen. C. Holbert",
        "chamber": "Senate"
      }, {
        "title": "Senator",
        "name": "Jahn, Cheri",
        "district": 20,
        "party": "Unaffiliated",
        "phone": "303-866-4856",
        "email": "cheri.jahn.senate@state.co.us",
        "occupation": "Senator/Small Business Owner",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_jahn-co-17.jpg?itok=vA7f92bX",
        "full_name": "Cheri Jahn",
        "last_name": "Jahn",
        "sponsor_name": "Sen. C. Jahn",
        "chamber": "Senate"
      }, {
        "title": "Senator",
        "name": "Jones, Matt",
        "district": 17,
        "party": "Democrat",
        "phone": "303-866-5291",
        "email": "senatormattjones@gmail.com",
        "occupation": "Legislator",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_jones-co-17.jpg?itok=IAc_0aEl",
        "full_name": "Matt Jones",
        "last_name": "Jones",
        "sponsor_name": "Sen. M. Jones",
        "chamber": "Senate"
      }, {
        "title": "Senator",
        "name": "Kagan, Daniel",
        "district": 26,
        "party": "Democrat",
        "phone": "303-866-4846",
        "email": "senatordanielkagan@gmail.com",
        "occupation": "Legislator",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_kagan-co-17.jpg?itok=xR5GUS1R",
        "full_name": "Daniel Kagan",
        "last_name": "Kagan",
        "sponsor_name": "Sen. D. Kagan",
        "chamber": "Senate"
      }, {
        "title": "Senator",
        "name": "Kefalas, John",
        "district": 14,
        "party": "Democrat",
        "phone": "303-866-4841",
        "email": "john.kefalas.senate@state.co.us",
        "occupation": "CSU Adjunct Faculty Member",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_s-kefalas%2C%20john.jpg?itok=MKK3cMfE",
        "full_name": "John Kefalas",
        "last_name": "Kefalas",
        "sponsor_name": "Sen. J. Kefalas",
        "chamber": "Senate"
      }, {
        "title": "Senator",
        "name": "Kerr, Andy",
        "district": 22,
        "party": "Democrat",
        "phone": "303-866-4859",
        "email": "SenatorAndyKerr@gmail.com",
        "occupation": "Teacher",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_kerr-co-17.jpg?itok=TYA0L-BL",
        "full_name": "Andy Kerr",
        "last_name": "Kerr",
        "sponsor_name": "Sen. A. Kerr",
        "chamber": "Senate"
      }, {
        "title": "Senator",
        "name": "Lambert, Kent",
        "district": 9,
        "party": "Republican",
        "phone": "303-866-4835",
        "email": "senatorlambert@comcast.net",
        "occupation": "USAF (Retired)",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_lambert-co-17.jpg?itok=bTv0rGGK",
        "full_name": "Kent Lambert",
        "last_name": "Lambert",
        "sponsor_name": "Sen. K. Lambert",
        "chamber": "Senate"
      }, {
        "title": "Senator",
        "name": "Lundberg, Kevin",
        "district": 15,
        "party": "Republican",
        "phone": "303-866-4853",
        "email": "kevin@kevinlundberg.com",
        "occupation": "Owner, Video and Media Production Service",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_lundberg-co-17.jpg?itok=7RvI3oMC",
        "full_name": "Kevin Lundberg",
        "last_name": "Lundberg",
        "sponsor_name": "Sen. K. Lundberg",
        "chamber": "Senate"
      }, {
        "title": "Senator",
        "name": "Marble, Vicki",
        "district": 23,
        "party": "Republican",
        "phone": "303-866-4876",
        "email": "vicki.marble.senate@state.co.us",
        "occupation": "Business Owner",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_s-marble%2C%20vicki.jpg?itok=gH_sN_XN",
        "full_name": "Vicki Marble",
        "last_name": "Marble",
        "sponsor_name": "Sen. V. Marble",
        "chamber": "Senate"
      }, {
        "title": "Senator",
        "name": "Martinez Humenik, Beth",
        "district": 24,
        "party": "Republican",
        "phone": "303-866-4863",
        "email": "beth.martinezhumenik.senate@state.co.us",
        "occupation": "Educator",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_martinez_humenik-co-17.jpg?itok=PLs4T-is",
        "full_name": "Beth Martinez Humenik",
        "last_name": "Martinez Humenik",
        "sponsor_name": "Sen. B. Martinez Humenik",
        "chamber": "Senate"
      }, {
        "title": "Senator",
        "name": "Merrifield, Michael",
        "district": 11,
        "party": "Democrat",
        "phone": "303-866-6364",
        "email": "michael.merrifield.senate@state.co.us",
        "occupation": "Retired Teacher",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_s-merrifield%2C%20michael.jpg?itok=41_3WY36",
        "full_name": "Michael Merrifield",
        "last_name": "Merrifield",
        "sponsor_name": "Sen. M. Merrifield",
        "chamber": "Senate"
      }, {
        "title": "Senator",
        "name": "Moreno, Dominick",
        "district": 21,
        "party": "Democrat",
        "phone": "303-866-4857",
        "email": "dominick.moreno.senate@state.co.us",
        "occupation": "Legislator",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_moreno-co-17.jpg?itok=KGpsucZt",
        "full_name": "Dominick Moreno",
        "last_name": "Moreno",
        "sponsor_name": "Sen. D. Moreno",
        "chamber": "Senate"
      }, {
        "title": "Senator",
        "name": "Neville, Tim",
        "district": 16,
        "party": "Republican",
        "phone": "303-866-4873",
        "email": "tim.neville.senate@state.co.us",
        "occupation": "Insurance Agency Owner",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_nevilletim-co-17.jpg?itok=5V-Kf9fh",
        "full_name": "Tim Neville",
        "last_name": "Neville T.",
        "sponsor_name": "Sen. T. Neville",
        "chamber": "Senate"
      }, {
        "title": "Senator",
        "name": "Priola, Kevin",
        "district": 25,
        "party": "Republican",
        "phone": "303-866-4855",
        "email": "kpriola@gmail.com",
        "occupation": "Small Business Owner",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_priola-co-17.jpg?itok=YKAUvESI",
        "full_name": "Kevin Priola",
        "last_name": "Priola",
        "sponsor_name": "Sen. K. Priola",
        "chamber": "Senate"
      }, {
        "title": "Senator",
        "name": "Scott, Ray",
        "district": 7,
        "party": "Republican",
        "phone": "303-866-3077",
        "email": "ray.scott.senate@state.co.us",
        "occupation": "Business Owner",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_scott-co-17.jpg?itok=WrYSLBzD",
        "full_name": "Ray Scott",
        "last_name": "Scott",
        "sponsor_name": "Sen. R. Scott",
        "chamber": "Senate"
      }, {
        "title": "Senator",
        "name": "Smallwood, Jim",
        "district": 4,
        "party": "Republican",
        "phone": "303-866-4869",
        "email": "senatorsmallwood@gmail.com",
        "occupation": "Insurance/Small Business Owner",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_smallwood-co-17.jpg?itok=c9wlAcuZ",
        "full_name": "Jim Smallwood",
        "last_name": "Smallwood",
        "sponsor_name": "Sen. J. Smallwood",
        "chamber": "Senate"
      }, {
        "title": "Senator",
        "name": "Sonnenberg, Jerry",
        "district": 1,
        "party": "Republican",
        "phone": "303-866-6360",
        "email": "senatorsonnenberg@gmail.com",
        "occupation": "Farmer/Rancher",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_sonnenberg-co-17.jpg?itok=dLQzfKEz",
        "full_name": "Jerry Sonnenberg",
        "last_name": "Sonnenberg",
        "sponsor_name": "Sen. J. Sonnenberg",
        "chamber": "Senate"
      }, {
        "title": "Senator",
        "name": "Tate, Jack",
        "district": 27,
        "party": "Republican",
        "phone": "303-866-4883",
        "email": "jack.tate.senate@state.co.us",
        "occupation": "Small Business Owner",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_tate-co-17.jpg?itok=c-lvVRMV",
        "full_name": "Jack Tate",
        "last_name": "Tate",
        "sponsor_name": "Sen. J. Tate",
        "chamber": "Senate"
      }, {
        "title": "Senator",
        "name": "Todd, Nancy",
        "district": 28,
        "party": "Democrat",
        "phone": "303-866-3432",
        "email": "nancy.todd.senate@state.co.us",
        "occupation": "Retired Teacher",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_todd-co-17.jpg?itok=_h51gyXW",
        "full_name": "Nancy Todd",
        "last_name": "Todd",
        "sponsor_name": "Sen. N. Todd",
        "chamber": "Senate"
      }, {
        "title": "Senator",
        "name": "Williams, Angela",
        "district": 33,
        "party": "Democrat",
        "phone": "303-866-4864",
        "email": "angela.williams.senate@state.co.us",
        "occupation": "Legislator",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_williamsangela-co-17.jpg?itok=jLorWT3z",
        "full_name": "Angela Williams",
        "last_name": "Williams A.",
        "sponsor_name": "Sen. A. Williams",
        "chamber": "Senate"
      }, {
        "title": "Senator",
        "name": "Zenzinger, Rachel",
        "district": 19,
        "party": "Democrat",
        "phone": "303-866-4840",
        "email": "senatorrachelz@gmail.com",
        "occupation": "Education",
        "headshot": "https://leg.colorado.gov/sites/default/files/styles/width_300/public/2018a_rsz_zenzinger-co-17.jpg?itok=7htzvNly",
        "full_name": "Rachel Zenzinger",
        "last_name": "Zenzinger",
        "sponsor_name": "Sen. R. Zenzinger",
        "chamber": "Senate"
      }]);
    });
};
